# Generated by Django 3.1.3 on 2020-11-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0002_auto_20201126_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollections',
            name='favourite_genres',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
