# Generated by Django 3.1.3 on 2020-11-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0003_auto_20201126_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollections',
            name='favourite_genres',
            field=models.BooleanField(default=0),
        ),
    ]
